name: Run trader

on:
  schedule:
    - cron: "*/30 * * * *"  # 每 30 分鐘執行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy requests ta-lib-binary

      - name: Run trade.py
        env:
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python trade.py