name: trader

on:
  schedule:
    - cron: "*/15 * * * *"  # 每 15 分鐘執行一次
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
      BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get install -y libta-lib0 libta-lib-dev
          pip install numpy requests TA-Lib

      - name: Run trader
        run: python trade.py