name: BingX Auto Trader

on:
  schedule:
    - cron: '*/30 * * * *'  # 每 30 分鐘執行一次
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run trader
      env:
        BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
        BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
      run: |
        python trade.py
