name: BingX Auto Trade

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run trading bot
        env:
          API_KEY: ${{ secrets.BINGX_API_KEY }}
          API_SECRET: ${{ secrets.BINGX_API_SECRET }}
        run: |
          echo "$API_KEY"
          echo "$API_SECRET"
          sed -i "s/你的API_KEY/$API_KEY/" config.json
          sed -i "s/你的API_SECRET/$API_SECRET/" config.json
          python trade.py